### ISSUE TITLE
NuGet Package Info

### ISSUE THREAD

**Issue by HybridSolutions** [koenvzeijl/AspNetCore.SassCompiler#10]
Hi,

great initiative! Trying it out. 
Just wanted to suggest to add Project Url to Nuget info since it's not appearing. Had to search google for this project ;) 

Also wanted to say I found a couple of issues while using it. In my case I have 3 .scss files:

_init.scss (imported in both plugins.scss and style.scss)
plugins.scss
style.scss

so unless I specify in the appsettings.json the path\\style.scss, the compiler keeps returning an error. 

The second issue is that the compiler is having some troubles with my Sass folder organization. I'm using Metronic Theme and this theme has multiple folders for components and plugins. It seems that your compiler tries to create a standalone components.css file when components scss files should be compiled into style.css. Of course, it doesn't work and returns an error since it lacks some variables and mixins.

style.scss contents:
---------------------
```
// Initialize
@import "init";
// Components
@import "components/components";

Generated components.css:

/* Error: Undefined variable.
 *   ,
 * 3 |   @each $color, $value in $colors {
 *   |                           ^^^^^^^
 *   '
 *   wwwroot\lib\bootstrap\scss\_root.scss 3:27           @import
 *   wwwroot\lib\metronic\components\components.scss 6:9  root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: "Error: Undefined variable.\a   \2577 \a 3 \2502    @each $color, $value in $colors {\a   \2502                            ^^^^^^^\a   \2575 \a   wwwroot\\lib\\bootstrap\\scss\\_root.scss 3:27           @import\a   wwwroot\\lib\\metronic\\components\\components.scss 6:9  root stylesheet";
}
```

Also, does this project support Sass Modules? I'm using Metronic Theme and they use Modules:

`@use 'sass:math';`

Thanks!

**Comment by sleeuwen** [comment]
Hi! Sorry for the late reply, it must have slipped through.

We actually do have the source repository linked in the nuget package. But today I tried searching for SassCompiler on nuget and found out there was a package "GeekInc.AspNetCore.SassCompiler". That is a different package as we publish it as "AspNetCore.SassCompiler". Are you using the former or the latter?

As for the issue you're having, this happens because of a convention from sass, which is that any file that doesn't start with a _ is considered an entry point. That is why a plugins.css will also be generated. You can safely rename the plugins.scss to _plugins.scss to stop it from generating the css and the @import's will keep working.

The sass modules are supported as well, as we support everything that is supported by dart-sass.
