### ISSUE TITLE
Non-Critical Question 

### ISSUE THREAD

**Issue by jakenuts** [koenvzeijl/AspNetCore.SassCompiler#115]
So I've been trying to get a handle on how to use sass in both web project and several RCL projects that get composed into it. Having tried all the various packages and extensions this one remains the easiest to use and the most seamless. I would love to be able to configure more than one project/path and watch that, but that's for another day. 

My question is, when I have this package installed and configure a source/target path the css files automatically get created if they don't exist. Similarly if I delete the css files either at design time or runtime *!!?) they are immediately updated. I can't for the life of me figure out how that is happening and since there are no msbuild or vs2022 logs/output at design time there isn't a clear way to track which system is making it happen. Oddly this does not work if the css file already exists and I update the scss, then I have to build to update it. That would be amazing but since it's all magic I have no clue if its possible.

Thanks so much,

James

**Comment by sleeuwen** [comment]
Hi @jakenuts ,

It would sound like there is another program that is generating the css files occasionally, this package doesn't do anything special at design time, but I will describe in which cases we generate the css files.

1. When the package is installed in a project, a MSBuild target is automatically added for that project that will run the sass command on your files when you build your project. This is defined in the [AspNetCore.SassCompiler.targets](https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/master/AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.targets#L10-L27) file.
2. If you add `.AddSassCompiler()` in your startup we will run the sass command using `--watch`, so that it will automatically recompile the scss files whenever one changes.

What happens if you remove the package reference to this package from your projects and then delete the css files, are they still getting generated or not anymore? If not then maybe there is something going on that triggers the target when it shouldn't (maybe one of the BeforeTargets is included during the design time build or something like that).

**Comment by jakenuts** [comment]
Thanks! If I remove the package, the files are no longer generated at design time. Not sure how that is happening with the package but as far as I know there are no special extensions or packages that might be the culprit.

**Comment by Rollerbeetle** [comment]
> * When the package is installed in a project, a MSBuild target is automatically added for that project that will run the sass command on your files when you build your project. This is defined in the [AspNetCore.SassCompiler.targets](https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/master/AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.targets#L10-L27) file.

From what i gathered there are cases where some of those targets get run on design time. 

https://github.com/NuGet/Home/issues/11958#issuecomment-1180679942

**Comment by sleeuwen** [comment]
Hi @Rollerbeetle  Thanks for pointing us to that issue. I've added the condition they suggest to the compile sass target so it won't run during design time builds anymore.
