### ISSUE TITLE
Version stamp on generated files

### ISSUE THREAD

**Issue by Martin-Andersen** [koenvzeijl/AspNetCore.SassCompiler#12]
Are there planes for creating version stamps on the generated files? Then your SassCompiler would be a complete soulution without any node or other npm packages.

Anyway thanks for making this great nuget packages

**Comment by sleeuwen** [comment]
Hi! Thanks for your interest in this project.
Currently we do not have any plans for version stamps on the generated files (I take it you mean things like site.[hash].css). 
We think the default `asp-append-version` tag helper is a great replacement for this. Please let us know if that would work for you too.

**Comment by Martin-Andersen** [comment]
I am working a lot with blazor wasm at the moment so I can't use the asp-append-version tag

**Comment by sleeuwen** [comment]
You're right, in blazor wasm the tag helper isn't available.
In that case I don't see a good way we could add version stamps to the file as the files need to be referenced in the index.html file (other than finding the link tags in the html and updating them, which isn't something we intend to do).

Also, it seems to me this is something that should be fixed in general either by the asp.net team or in a specific package as this is not only an issue for sass/scss but also for standard css files.
