### ISSUE TITLE
Can you install this Lib as a dev dependency

### ISSUE THREAD

**Issue by mikes-gh** [koenvzeijl/AspNetCore.SassCompiler#160]
**Is your feature request related to a problem? Please describe.**
If I use PrivateAssets="all" my app crashes.
It is looking for the lib at runtime even though I only use it for generating assets at build time

**Describe the solution you'd like**
Ability to use Lib as a dev dependency in order to reduce app payload

**Comment by adiessl** [comment]
We are specifying `<PrivateAssets>All</PrivateAssets>` for the NuGet package `AspNetCore.SassCompiler` in our `.csproj` files and it works for us at runtime. Therefore it is generally possible.

How is your setup? Are you specifying any options in `appsettings.json`? Or are you using `sasscompiler.json` as we are? Are you maybe using `services.AddSassCompiler();` outside of `DEBUG` environment? What is the error you get at runtime?

**Comment by mikes-gh** [comment]
We are using `sasscompiler.json`
No `services.AddSassCompiler();`

Error is here

https://github.com/MudBlazor/MudBlazor/pull/7933#issuecomment-1863130585

Currently the PR I have removed the <PrivateAssets>All</PrivateAssets> in order to get it to work

**Comment by mikes-gh** [comment]
Its because of this https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/2d7ff3808660c9a557a00d4f943055ac365460f7/AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.props#L29
So event If I set PrivateAssets="all" all it still modifies the assemblyinfo with an unknown namespace

**Comment by sleeuwen** [comment]
Hi @mikes-gh ,

It indeed looks like the watcher is determined to be enabled and thus will generate the assembly attribute. It is only enabled in Debug configuration, but I noticed that you're using it in a RazorClassLibrary so then I think it should indeed also be disabled in Debug mode.

One way you can force it to disable the watcher is to add `<SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>` inside of a `<PropertyGroup>`, that way it also won't generate the assembly attribute anymore.

But I think this should be disabled by default for a RazorClassLibrary. When we added support for those projects we also added a check that disables the watcher if the project it was used in is not an executable. However, that seemed to have caused to also disable the watcher in projects where it shouldn't (see #77 and [how we fixed it](https://github.com/koenvzeijl/AspNetCore.SassCompiler/commit/e51b12e82de86bab9139155c12d75e807d2a85ca))

I don't have enough information why that caused an issue and broke it for some people, one thing that comes to mind is maybe we should do a case-insensitive check so that if `OutputType` was lowercase `exe` it would still enable the watcher. But I don't know if that really was the case at the time, or that there is another issue with this check, which makes me hesitant to add it back.

**Comment by mikes-gh** [comment]
> Hi @mikes-gh ,
> 
> It indeed looks like the watcher is determined to be enabled and thus will generate the assembly attribute. It is only enabled in Debug configuration, but I noticed that you're using it in a RazorClassLibrary so then I think it should indeed also be disabled in Debug mode.
> 
> One way you can force it to disable the watcher is to add `<SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>` inside of a `<PropertyGroup>`, that way it also won't generate the assembly attribute anymore.
> 
> But I think this should be disabled by default for a RazorClassLibrary. When we added support for those projects we also added a check that disables the watcher if the project it was used in is not an executable. However, that seemed to have caused to also disable the watcher in projects where it shouldn't (see #77 and [how we fixed it](https://github.com/koenvzeijl/AspNetCore.SassCompiler/commit/e51b12e82de86bab9139155c12d75e807d2a85ca))
> 
> I don't have enough information why that caused an issue and broke it for some people, one thing that comes to mind is maybe we should do a case-insensitive check so that if `OutputType` was lowercase `exe` it would still enable the watcher. But I don't know if that really was the case at the time, or that there is another issue with this check, which makes me hesitant to add it back.

Its actually a blazor class library.  Not sure if that matters.  Thanks for the info it was very helpful

**Comment by mikes-gh** [comment]
@sleeuwen 
> One way you can force it to disable the watcher is to add <SassCompilerEnableWatcher>false</SassCompilerEnableWatcher> inside of a <PropertyGroup>, that way it also won't generate the assembly attribute anymore.

That solved it no more runtime dependencies :-)

**Comment by ViRuSTriNiTy** [comment]
Somehow this issue is a very strange one. For me, it is unclear why I even need to set `SassCompilerEnableWatcher` in an Razor Component Library Project because it should be set to `false` automatically as implemented in `.props` file, see
https://github.com/koenvzeijl/AspNetCore.SassCompiler/blob/6e063ee468b5429a6a066d31c0b59ae0dab6577b/AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.props#L30.

I tried to debug why the condition is not true. It seems like `$(OutputType)` is empty when the `.props` file is imported, but when I log the property via 

<Message Text="$(OutputType)" Importance="high" />

in the RCL project, the output is `Library`.

Why on earth is `$(OutputType)` empty when the `.props` file is imported?
