### ISSUE TITLE
Make SassCompilerOptions public to configure Options in code instead of appsettings

### ISSUE THREAD

**Issue by wvdhouten** [koenvzeijl/AspNetCore.SassCompiler#45]
**Is your feature request related to a problem? Please describe.**
The current implementation forces to configure the options through an appsettings.json file. A lot of other middleware allows a "services.Configure<xy>()" solution, when the Options are public. 

**Describe the solution you'd like**
I reckon that making SassCompilerOptions public would allow for overriding some variables without needing to update an appsettings.

**Describe alternatives you've considered**
None.

**Additional context**
(Having appsettings as copy-if-newer could override some changed files on servers)

**Comment by sleeuwen** [comment]
Hi, Thanks for your interest in the project.

There is a reason we made the options class internal and don't allow you to configure it in code, and that is because we run the compilation in two different times, once during development and once during publish, and we have to make sure they use the same configuration.
During development you can run the compiler using the `.AddSassCompiler()` services extension method. This will make it watch for changes to the files and recompile when there are changes. This method will run in the same process and your app and has access to the IConfiguration instance like everything else.
During publish (e.g. `dotnet publish`) we compile the sass/scss through an MSBuild task so that it will be included in the publish directory. This being an MSBuild task, it doesn't have access to the IConfiguration instance and cannot see any configuration changes you would have made in startup. To ensure consistent behavior between the two, in both cases we will read from the appsettings directly to populate our options class.
If we would allow this change that would mean the publish step can use different settings than during debugging, which makes it hard to understand why your scss doesn't get compiled on publish if you're not aware of this behavior. 

If the only thing you're worried about is having to set the appsettings as copy-if-newer, I believe we read the appsettings in the project directory during publish so it wouldn't need to be copy-if-newer for the compilation to work.

**Comment by wvdhouten** [comment]
OK, I guess I could add an additional file called sasscompilerconfig.json, and add that to my config loader. I suppose that would solve the "Copy if newer" issue
